### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by morinted** [ramalho/calendar.js#5]
There is no license specified for the software in the README nor the package.json.

**Comment by abradley2** [comment]
This is a significant issue. By default it is _All rights Reserved_ which is a potential legal hazard to anyone using this.

@ramalho would you please clarify?

**Comment by ramalho** [comment]
Thank you for your interest. I've added an MIT license.

**Comment by ramalho** [comment]
Added standard MIT LICENSE file.

**Comment by ramalho** [comment]
@morinted, @abradley2: I've added a standard MIT LICENSE to the calendar.js repo. Thanks for the heads up!
